// <auto-generated />
using System;
using System.Text.Json;
using MedicalDiagnosticSystem.MedicalDiagnostic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalDiagnostic.Data.Migrations
{
    [DbContext(typeof(MedicalDiagnosticDbContext))]
    [Migration("20260225134545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActionDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_details");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("LogId", "CreatedAt");

                    b.HasIndex("Action");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DoctorId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ClinicalResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DiagnosisCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_case_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExplainabilityData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("explainability_data");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prediction");

                    b.Property<string>("Probabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("probabilities");

                    b.Property<double?>("ProcessingTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("processing_time_ms");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisCaseId");

                    b.ToTable("clinical_results", (string)null);
                });

            modelBuilder.Entity("ClinicalSymptom", b =>
                {
                    b.Property<Guid>("SymptomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("symptom_id");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("text")
                        .HasColumnName("blood_pressure");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("FamilyHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("family_history");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("SmokingHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("smoking_history");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("symptoms");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.HasKey("SymptomId");

                    b.HasIndex("CaseId");

                    b.ToTable("clinical_symptoms", (string)null);
                });

            modelBuilder.Entity("ImagingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DiagnosisCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_case_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExplainabilityData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("explainability_data");

                    b.Property<byte[]>("GradCamHeatmapImage")
                        .HasColumnType("bytea")
                        .HasColumnName("grad_cam_heatmap_image");

                    b.Property<DateTime?>("GradCamImageGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grad_cam_image_generated_at");

                    b.Property<byte[]>("GradCamOverlayImage")
                        .HasColumnType("bytea")
                        .HasColumnName("grad_cam_overlay_image");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prediction");

                    b.Property<string>("Probabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("probabilities");

                    b.Property<double?>("ProcessingTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("processing_time_ms");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisCaseId");

                    b.ToTable("imaging_results", (string)null);
                });

            modelBuilder.Entity("LabTest", b =>
                {
                    b.Property<Guid>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lab_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lab_name");

                    b.Property<string>("ReferenceRanges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reference_ranges");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("test_date");

                    b.Property<string>("TestResults")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("test_results");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("LabId");

                    b.HasIndex("CaseId");

                    b.HasIndex("TestDate");

                    b.ToTable("lab_tests", (string)null);
                });

            modelBuilder.Entity("LaboratoryResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DiagnosisCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_case_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExplainabilityData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("explainability_data");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prediction");

                    b.Property<string>("Probabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("probabilities");

                    b.Property<double?>("ProcessingTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("processing_time_ms");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisCaseId");

                    b.ToTable("laboratory_results", (string)null);
                });

            modelBuilder.Entity("MedicalDiagnosticSystem.MedicalDiagnostic.Data.Entities.DiagnosisCase", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DiagnosisType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_type");

                    b.Property<string>("DoctorDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("doctor_diagnosis");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text")
                        .HasColumnName("doctor_notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CaseId", "CreatedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("diagnosis_cases", (string)null);
                });

            modelBuilder.Entity("MedicalDiagnosticSystem.MedicalDiagnostic.Data.Entities.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("HospitalAffiliation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hospital_affiliation");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("DoctorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("MedicalDiagnosticSystem.MedicalDiagnostic.Data.Entities.MedicalImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<int?>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<JsonDocument>("DicomMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("dicom_metadata");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_type");

                    b.Property<int?>("InstanceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("instance_number");

                    b.Property<string>("InstanceUid")
                        .HasColumnType("text")
                        .HasColumnName("instance_uid");

                    b.Property<bool>("IsPreprocessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preprocessed");

                    b.Property<string>("Modality")
                        .HasColumnType("text")
                        .HasColumnName("modality");

                    b.Property<string>("PixelSpacing")
                        .HasColumnType("text")
                        .HasColumnName("pixel_spacing");

                    b.Property<int?>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<string>("ScanArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scan_area");

                    b.Property<string>("SeriesDescription")
                        .HasColumnType("text")
                        .HasColumnName("series_description");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("integer")
                        .HasColumnName("series_number");

                    b.Property<string>("SeriesUid")
                        .HasColumnType("text")
                        .HasColumnName("series_uid");

                    b.Property<decimal?>("SliceThickness")
                        .HasColumnType("numeric")
                        .HasColumnName("slice_thickness");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("study_date");

                    b.Property<string>("StudyUid")
                        .HasColumnType("text")
                        .HasColumnName("study_uid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("WindowCenter")
                        .HasColumnType("integer")
                        .HasColumnName("window_center");

                    b.Property<int?>("WindowWidth")
                        .HasColumnType("integer")
                        .HasColumnName("window_width");

                    b.HasKey("ImageId");

                    b.HasIndex("CaseId");

                    b.ToTable("medical_images", (string)null);
                });

            modelBuilder.Entity("MedicalDiagnosticSystem.MedicalDiagnostic.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("PatientId");

                    b.HasIndex("PatientCode")
                        .IsUnique();

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("UnifiedDiagnosisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string[]>("ContributingModules")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("contributing_modules");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DiagnosisCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_case_id");

                    b.Property<string>("EnsembleProbabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ensemble_probabilities");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<string>("ExplainabilitySummary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("explainability_summary");

                    b.Property<string>("FinalDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_diagnosis");

                    b.Property<double>("OverallConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_confidence");

                    b.Property<string[]>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recommendations");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.Property<double?>("TotalProcessingTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_processing_time_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisCaseId");

                    b.HasIndex("FinalDiagnosis");

                    b.ToTable("unified_diagnosis_results", (string)null);
                });

            modelBuilder.Entity("MedicalDiagnosticSystem.MedicalDiagnostic.Data.Entities.MedicalImage", b =>
                {
                    b.HasOne("MedicalDiagnosticSystem.MedicalDiagnostic.Data.Entities.DiagnosisCase", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .HasPrincipalKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
